cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: cristian
      secret-key: cristian
    end-point:
      host: http://localhost:4566
      name: my-queue
      url: http://localhost:4566/000000000000/my-queue